# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: A Field Guide to Elephpants
latinname: Elephpas hypertextus
hostname: localhost:8000
https: false
# Please keep the subspecies alphabetized
subspecies:
    afup:
        common: "AFUP"
        latin: "gallici"
    amsterdamphp:
        common: "AmsterdamPHP"
        latin: "amstelodami"
    cakephp:
        common: "CakePHP"
        latin: "pistrini"
    check24:
        common: "CHECK24"
        latin: "collationis"
    confoo:
        common: "ConFoo"
        latin: "fooianum"
    darkmira:
        common: "Darkmira PHP Tour"
        latin: "unitas"
    dpc:
        common: "Dutch PHP Conference"
        latin: "batavici"
    gold:
        common: "Gold"
        latin: "auri"
    globalis:
        common: "Globalis"
        latin: "globi"
    heroku:
        common: "Heroku"
        latin: "herokai"
    laravel:
        common: "Laravel"
        latin: "laraveli"
    linuxforphp:
        common: "Linux for PHP"
        latin: "linuxi"
    magento:
        common: "Magento"
        latin: "mercatoris"
    oracle:
        common: "Oracle"
        latin: "oraculi"
    phparch:
        common: "PHP|Architect"
        latin: "architecti"
    phpbenelux:
        common: "PHPBenelux"
        latin: "belgerlandemburgi"
    phpclasses:
        common: "PHP Classes"
        latin: "decuriae"
    phppl:
        common: "PHPCon Poland"
        latin: "polski"
    phpconjapan:
        common: "PHPCON Japan"
        latin: "colloquiumiapona"
    phproundtable:
        common: "PHP Roundtable"
        latin: "circumensi"
    phpstorm:
        common: "PhpStorm"
        latin: "gagatescerebellum"
    phpwomen:
        common: "PHP Women"
        latin: "feminae"
    phpyorkshire:
        common: "PHP Yorkshire"
        latin: "eboraci"
    roave:
        common: "Roave"
        latin: "roavorum"
    sunshinephp:
        common: "SunshinePHP"
        latin: "solis"
    haphpy:
        common: "HaPHPy"
        latin: "natalis"
    rainbow:
        common: "Rainbow"
        latin: "arcus"
    shopware:
        common: "Shopware"
        latin: "shopwari"
    symfony:
        common: "Symfony"
        latin: "symphoniae"
    zend:
        common: "Zend"
        latin: "zeevandi"
    zf2:
        common: "Zend Framework"
        latin: "zendframeworki"
    phpvegas:
        common: "PHP Vegas"
        latin: "fabulosum"
relatedspecies:
    hack:
        common: "pHackyderm"
        latin: "Elephpas cyberneticus"
    truenorthphp:
        common: "PHP Woolly Mammoth"
        latin: "Elephpas mammuthus"
